### ISSUE TITLE
Please help asap!

### ISSUE THREAD

**Issue by 1StarYelpReview** [Eskander/userscripts-collection#1]
So this could be something on my end, but i figured i would write this anyway. It seems that the auto play feature and the stretch video into full screen is not working. I am on chrome using your complete captcha removal, auto play and auto next and stretch videos in full screen scripts. I also have ads blocked.  It is just the autoplay and the stretch to full screen that is not working, everything else is working just fine.

**Comment by Eskander** [comment]
Google Chrome's autoplay policy disables playing videos automatically without user interaction. My previous workaround no longer works and I think I'll be dropping Chrome support if there's no solution in the near future.
Ref: https://developers.google.com/web/updates/2017/09/autoplay-policy-changes

**Comment by 1StarYelpReview** [comment]
Thank you for the reply, i tried it in firefox and now everything works except the auto fullscreen.
