### ISSUE TITLE
KissManga

### ISSUE THREAD

**Issue by taylordwright44** [Eskander/userscripts-collection#2]
This isn't actually an issue, but KissManga.com recently added the same captcha your captcha-remover userscript blocks on kissanime.ru

Basically I'm too lazy to install git on this computer to do a pull request(I'm using my Windows boot), so I was wondering if you could add // @match        *://kissmanga.com/* to your userscript for other users who use kissmanga. I already did it on mine and verified your script indeed removes the manga site's captchas as well, so you can just paste it in and it'll work. Thanks for the script, mate.

**Comment by Eskander** [comment]
The script shouldn't work on Kissmanga. It uses Kissanime's captcha-free server.
Nonetheless, I tried the changes you suggested and indeed it didn't work.
By the way, you can always use GitHub's online tools to submit a PR without installing anything on your PC.

**Comment by taylordwright44** [comment]
Apologies, it seemed to be a coincidence that I didn't get CAPTCHA several times in a row after adding Kissmanga to your script. I found out later you're correct.
